version: 2.1
jobs:
  test:
    machine:
      enabled: true
    steps:
      - run: echo "Test can run here!"
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Install Java & Maven
          command: ssh $SSH_USER@$SSH_HOST "sudo apt-get update && sudo apt-get install -y curl git && sudo apt-get install -y openjdk-8-jdk" 
      - run:
          name: Pull git 
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project && git pull"
      - run:
          name: install maven
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project/bottles && sudo apt-get install -y maven"
      - run:
          name: Deploy Application
          command: ssh $SSH_USER@$SSH_HOST "cd ~/Fundamental_Project/bottles && mvn verify"
      - run:
          name: Run application 
          command: ssh $SSH_USER@$SSH_HOST "cd ~/~/Fundamental_Project/bottles && mvn -Dmaven.test.skip=true spring-boot:run" 
workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
